version: "3"

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./:/go/src/github.com/sivchari/chat-answer
    ports:
      - "8080:8080"
  buf:
    build:
      context: .
      dockerfile: docker/buf/Dockerfile
    working_dir: /usr/src/chat-answer
    volumes:
      - ./:/usr/src/chat-answer
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    working_dir: /usr/src/chat-answer/front
    volumes:
      - ./front:/usr/src/chat-answer
    ports:
      - "5173:5173"
